"""Issue implementation orchestrator — turns issues into PRs via Copilot CLI."""

import logging
import time

from copilot import run_copilot
from git import (
    cleanup_branch_worktree,
    cleanup_worktree,
    commit_and_push,
    create_branch_worktree,
    create_worktree,
)
from github import (
    comment_on_issue,
    create_pull_request,
    get_issue,
    get_pr,
    get_token,
    get_unresolved_threads,
)

logger = logging.getLogger(__name__)

IMPLEMENT_PROMPT_TEMPLATE = """\
Implement the following GitHub issue in {repo}.

## Issue #{issue_number}: {title}

{body}

Use the implement skill for guidelines on how to make changes.
"""

FIX_PROMPT_TEMPLATE = """\
Fix the review feedback on PR #{pr_number} in {repo}.

The review bot found the following issues that need to be addressed:

{threads}

Use the implement skill for guidelines on how to make changes.
"""


async def implement_issue(
    *,
    repo: str,
    issue_number: int,
    model: str = "gpt-5.4",
    reasoning_effort: str = "high",
) -> dict:
    """Implement a GitHub issue: create branch → run CLI → push → create PR."""
    logger.info("Implementing issue %s#%d", repo, issue_number)
    start = time.monotonic()
    repo_url = f"https://github.com/{repo}.git"
    branch_name = f"agent/issue-{issue_number}"

    token = await get_token()
    issue = await get_issue(repo, issue_number)

    # Trust boundary: only implement issues from trusted authors to prevent
    # prompt injection via attacker-controlled issue bodies
    trusted_roles = {"OWNER", "MEMBER", "COLLABORATOR"}
    author_role = issue.get("author_association", "NONE")
    if author_role not in trusted_roles:
        raise ValueError(
            f"Issue #{issue_number} author has role '{author_role}' — "
            f"only {trusted_roles} are trusted for autonomous implementation"
        )

    try:
        worktree_path = await create_branch_worktree(branch_name, repo_url)

        prompt = IMPLEMENT_PROMPT_TEMPLATE.format(
            repo=repo,
            issue_number=issue_number,
            title=issue["title"],
            body=issue.get("body") or "(no description)",
        )

        result = await run_copilot(
            worktree_path,
            prompt,
            model=model,
            effort=reasoning_effort,
            gh_token=token,
        )

        sha = await commit_and_push(
            worktree_path,
            message=f"feat: implement #{issue_number} — {issue['title']}",
            token=token,
            repo=repo,
            branch=branch_name,
        )

        pr = await create_pull_request(
            repo,
            title=f"feat: {issue['title']}",
            body=(f"Implements #{issue_number}.\n\nAutonomously generated by the homelab agent."),
            head=branch_name,
            base="main",
        )

        # Trigger review — if this fails, surface partial success with the PR info
        try:
            await comment_on_issue(repo, pr["number"], "/review")
        except Exception:
            logger.warning("Failed to trigger /review on PR #%d", pr["number"])
            return {
                "status": "partial",
                "pr_number": pr["number"],
                "pr_url": pr["html_url"],
                "commit_sha": sha,
                "elapsed_seconds": time.monotonic() - start,
                "premium_requests": result.total_premium_requests,
                "error": "PR created but failed to trigger /review comment",
            }

        elapsed = time.monotonic() - start
        logger.info(
            "Implementation complete for %s#%d in %.1fs → PR #%d",
            repo,
            issue_number,
            elapsed,
            pr["number"],
        )

        return {
            "pr_number": pr["number"],
            "pr_url": pr["html_url"],
            "commit_sha": sha,
            "elapsed_seconds": elapsed,
            "premium_requests": result.total_premium_requests,
        }

    finally:
        await cleanup_branch_worktree(branch_name)


async def fix_pr(
    *,
    repo: str,
    pr_number: int,
    model: str = "gpt-5.4",
    reasoning_effort: str = "high",
) -> dict:
    """Fix review feedback on a PR: checkout → run CLI → push → re-trigger review."""
    logger.info("Fixing PR %s#%d", repo, pr_number)
    start = time.monotonic()
    repo_url = f"https://github.com/{repo}.git"

    token = await get_token()

    threads = await get_unresolved_threads(repo, pr_number)
    if not threads:
        return {"status": "nothing_to_fix", "pr_number": pr_number}

    pr_data = await get_pr(repo, pr_number)
    head_branch = pr_data["head"]["ref"]

    try:
        worktree_path = await create_worktree(pr_number, repo_url)

        prompt = FIX_PROMPT_TEMPLATE.format(
            repo=repo,
            pr_number=pr_number,
            threads=threads,
        )

        result = await run_copilot(
            worktree_path,
            prompt,
            model=model,
            effort=reasoning_effort,
            gh_token=token,
        )

        sha = await commit_and_push(
            worktree_path,
            message=f"fix: address review feedback on #{pr_number}",
            token=token,
            repo=repo,
            branch=head_branch,
        )

        # Trigger re-review — if this fails, surface partial success
        try:
            await comment_on_issue(repo, pr_number, "/review")
        except Exception:
            logger.warning("Failed to trigger /review on PR #%d", pr_number)
            return {
                "status": "partial",
                "pr_number": pr_number,
                "commit_sha": sha,
                "elapsed_seconds": time.monotonic() - start,
                "premium_requests": result.total_premium_requests,
                "error": "Fix pushed but failed to trigger /review comment",
            }

        elapsed = time.monotonic() - start
        logger.info("Fix complete for %s#%d in %.1fs", repo, pr_number, elapsed)

        return {
            "status": "fixed",
            "pr_number": pr_number,
            "commit_sha": sha,
            "elapsed_seconds": elapsed,
            "premium_requests": result.total_premium_requests,
        }

    finally:
        await cleanup_worktree(pr_number)
