services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.1.2-alpine@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/broker/uptime' -C 1 -W 5 >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "100.100.146.119:1883:1883"
      - "100.100.146.119:9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - TZ=Europe/London
