services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.1.2
    restart: unless-stopped
    ports:
      - "100.100.146.119:1883:1883"
      - "100.100.146.119:9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - TZ=Europe/London
